name: Douyin-Keeper
on:
  workflow_dispatch:  # 支持手动一键测试
  schedule:
    - cron: '2 12 * * *'  # 北京时间每天19:24自动执行

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      COOKIES: ${{ secrets.COOKIES }}
      TARGET_NAME: ${{ secrets.TARGET_NAME }}
      MSG: ${{ secrets.MSG }}
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 配置Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 安装依赖 + 安装playwright浏览器
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium
          playwright install-deps chromium

      - name: 执行一次性续火花脚本
        run: python send_once.py
